deployment:
  imageURL: nagaraj411/shipping  # ğŸ“¦ Custom Shipping Docker image URL
  imageVersion: v1  # ğŸ“¦ Custom Shipping Docker image version
hpa:
  maxReplicas: 10 # ğŸ”¼ Maximum pods
  utilisation: 10 # ğŸ¯ Target 10% CPU usage